#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("mPassword.Droid.Resource", IsApplication=true)]

namespace mPassword.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::mPassword.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::mPassword.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int listDay = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int bg_login = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int bg_main = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int bg_register = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int btn_login = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int btn_login_bg = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int input_login = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int input_login_hint = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int input_register = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int white = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080021
			public const int action_logout = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int action_update_profile = 2131230752;
			
			// aapt resource value: 0x7f08000d
			public const int btnCancel = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int btnDelete = 2131230734;
			
			// aapt resource value: 0x7f08001e
			public const int btnLinkToLoginScreen = 2131230750;
			
			// aapt resource value: 0x7f08001a
			public const int btnLinkToRegisterScreen = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int btnLogin = 2131230745;
			
			// aapt resource value: 0x7f08001d
			public const int btnRegister = 2131230749;
			
			// aapt resource value: 0x7f08000c
			public const int btnSave = 2131230732;
			
			// aapt resource value: 0x7f08001c
			public const int confirm_password = 2131230748;
			
			// aapt resource value: 0x7f080004
			public const int edtATMPassword = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int edtAccountName = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int edtAccountNumber = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int edtBankName = 2131230722;
			
			// aapt resource value: 0x7f080016
			public const int edtConfirmNewPass = 2131230742;
			
			// aapt resource value: 0x7f080006
			public const int edtEbankPassword = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int edtEbankUsername = 2131230725;
			
			// aapt resource value: 0x7f080015
			public const int edtNewPass = 2131230741;
			
			// aapt resource value: 0x7f080009
			public const int edtNote = 2131230729;
			
			// aapt resource value: 0x7f080014
			public const int edtOldPass = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int edtPassword = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int edtSecurityAnswer = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int edtSecurityQuestion = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int edtUpdatedDate = 2131230731;
			
			// aapt resource value: 0x7f08001f
			public const int edtUrl = 2131230751;
			
			// aapt resource value: 0x7f080012
			public const int edtUsername = 2131230738;
			
			// aapt resource value: 0x7f08001b
			public const int expandListView = 2131230747;
			
			// aapt resource value: 0x7f080001
			public const int imgButtonWarning = 2131230721;
			
			// aapt resource value: 0x7f08000f
			public const int lblCategoryName = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int lblListItem = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int lblQuantity = 2131230736;
			
			// aapt resource value: 0x7f080018
			public const int password = 2131230744;
			
			// aapt resource value: 0x7f08000a
			public const int spinnerDuration = 2131230730;
			
			// aapt resource value: 0x7f080017
			public const int username = 2131230743;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BankDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CategoryRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ComputerDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EmailDetail = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SignUp = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int WebDetail = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MenuItems = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000f
			public const int action_logout = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int action_update_profile = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int btn_link_to_login = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int btn_link_to_register = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int btn_login = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int btn_logout = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int btn_register = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int day_prompt = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int hint_confirm_password = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int hint_password = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int hint_username = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int name = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int welcome = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
